name: build-test-push

on:
  push:

jobs:

  build-test-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag interview

    - name: Run Docker Container
      run: docker run --rm -d --init -p 80:80 interview
  
    - name: run tests
      uses: liatrio/github-actions/apprentice-action@master
      
    - name: push to dockerhub
      run: docker push tkroll92/liatrio_apprenticeship:interview
      
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}